//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductsServiceBasedDBEntities : DbContext
    {
        public ProductsServiceBasedDBEntities()
            : base("name=ProductsServiceBasedDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aruhaz> Aruhaz { get; set; }
        public virtual DbSet<Gyarto> Gyarto { get; set; }
        public virtual DbSet<ID_Kapcsolo> ID_Kapcsolo { get; set; }
        public virtual DbSet<Termek> Termek { get; set; }
    }
}
