//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_Kapcsolo
    {
        public decimal Kapcsolo_ID { get; set; }
        public decimal Termek_ID { get; set; }
        public string Aruhaz_neve { get; set; }
    
        public virtual Aruhaz Aruhaz { get; set; }
        public virtual Termek Termek { get; set; }
    }
}
