//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termek()
        {
            this.ID_Kapcsolo = new HashSet<ID_Kapcsolo>();
        }
    
        public decimal Termek_ID { get; set; }
        public string Tipus { get; set; }
        public string Megnevezes { get; set; }
        public string Kiszereles { get; set; }
        public Nullable<decimal> Ar { get; set; }
        public string Leiras { get; set; }
        public string Gyarto_neve { get; set; }
    
        public virtual Gyarto Gyarto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ID_Kapcsolo> ID_Kapcsolo { get; set; }
    }
}
